language: cpp

before_script:
  - chmod +x cbp2make

script:
  - ./cbp2make  -targets Debug,Release,Test -in GTest.cbp -out Makefile
  - make
  - bin/Test/GTest
  - gcov -o obj/Test/src src/GTest.cpp

after_success:
  - bash <(curl -s https://codecov.io/bash)
